version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_redis
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: productos_redis_db
    ports:
      - "6060:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data_redis

  redis:
    image: redis:latest
    container_name: redis_spring
    ports:
      - "6379:6379"

volumes:
  postgres_data:
